"""
cross_validator.py - Fine-Gray 경쟁위험 모델 교차 검증 (Python vs R cmprsk::crr)

논문 제출 전 Python IPCW 근사 구현을 R cmprsk::crr() 결과와 비교하여
validation_status(VALIDATED / DISCREPANT / R_NOT_AVAILABLE)를 부여한다.

보안:
  - CSV에 INDI_DSCM_NO 등 환자 식별자를 포함하지 않음 (화이트리스트 컬럼만 내보내기)
  - 임시 파일은 tempfile.mkdtemp() 경로에 생성, 분석 후 cleanup_temp_files()로 삭제
"""
from __future__ import annotations

import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# 교차 검증에서 허용하는 컬럼 화이트리스트 (환자 식별자 제외)
_ALLOWED_COVARS = frozenset([
    'is_t1dm', 'is_t2dm_oha', 'is_t2dm_insulin', 'is_t2dm_nomed',
    'age_at_index', 'male', 'cci_score', 'bmi', 'income_q',
    'smk_current', 'smk_former', 'comp_hypoglycemia',
])

_DEFAULT_COVARS = ['is_t1dm', 'is_t2dm_oha', 'is_t2dm_insulin', 'is_t2dm_nomed',
                   'age_at_index', 'male']

# R 스크립트 실행 기본 타임아웃 (초)
_DEFAULT_R_TIMEOUT = 300


class CrossValidator:
    """Fine-Gray Python vs R cmprsk::crr() 교차 검증 파이프라인.

    일반적인 사용 흐름:
        cv = CrossValidator()
        csv_path = cv.export_csv_for_r(df_cr, event_type, 'dementia_event')
        r_path   = cv.generate_r_script(csv_path, 'dementia_event')
        r_result = cv.run_r_script(r_path)          # R 미설치 시 None
        cmp_df   = cv.compare_results(py_summary, r_result)
        cv.cleanup_temp_files([csv_path, r_path])
    """

    def export_csv_for_r(
        self,
        df_cr: pd.DataFrame,
        event_type: np.ndarray,
        outcome: str,
        covars: list[str] | None = None,
        output_dir: str | Path | None = None,
    ) -> Path:
        """분석 데이터를 R용 CSV로 내보낸다.

        Args:
            df_cr: run_competing_risks에서 사용된 전처리된 DataFrame
            event_type: 0=검열, 1=관심사건, 2=경쟁위험 (numpy int array)
            outcome: 결과변수명 (파일명 구분용)
            covars: 포함할 공변량 컬럼 목록 (None이면 _DEFAULT_COVARS 중 존재하는 것)
            output_dir: 출력 디렉토리 (None이면 tempfile.mkdtemp())

        Returns:
            저장된 CSV 파일 경로

        Raises:
            ValueError: 허용되지 않는 컬럼명(환자 식별자 등) 포함 시
        """
        if covars is None:
            covars = [c for c in _DEFAULT_COVARS if c in df_cr.columns]

        # 보안: 화이트리스트 검증
        forbidden = [c for c in covars if c not in _ALLOWED_COVARS]
        if forbidden:
            raise ValueError(
                f"CSV 내보내기 금지 컬럼 포함: {forbidden}. "
                "환자 식별자는 포함할 수 없습니다."
            )

        if output_dir is None:
            output_dir = Path(tempfile.mkdtemp(prefix='yod_cv_'))
        else:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)

        # 실제 존재하는 컬럼만 사용
        use_cols = [c for c in covars if c in df_cr.columns]
        if not use_cols:
            raise ValueError(f"사용 가능한 공변량 컬럼이 없습니다. df_cr 컬럼: {list(df_cr.columns)}")

        export_df = df_cr[['follow_up_years'] + use_cols].copy()
        export_df.insert(1, 'event_type', event_type)
        export_df = export_df.rename(columns={'follow_up_years': 'time'})

        # NaN/Inf 제거
        export_df = export_df.replace([np.inf, -np.inf], np.nan).dropna()
        export_df = export_df[export_df['time'] > 0]

        safe_outcome = re.sub(r'[^\w]', '_', outcome)
        csv_path = output_dir / f'cv_data_{safe_outcome}.csv'
        export_df.to_csv(csv_path, index=False)

        logger.info(
            "교차 검증 CSV 저장: %s (행 %d, 컬럼 %s)",
            csv_path, len(export_df), list(export_df.columns)
        )
        return csv_path

    def generate_r_script(
        self,
        csv_path: Path,
        outcome: str,
        output_dir: str | Path | None = None,
    ) -> Path:
        """cmprsk::crr() 호출 R 스크립트를 자동 생성한다.

        R 스크립트는 CSV를 읽어 crr() 실행 후 결과를 JSON으로 저장한다.

        Args:
            csv_path: export_csv_for_r()가 반환한 CSV 경로
            outcome: 결과변수명 (스크립트 주석 및 파일명 구분용)
            output_dir: 출력 디렉토리 (None이면 csv_path와 같은 디렉토리)

        Returns:
            생성된 R 스크립트 경로
        """
        csv_path = Path(csv_path)
        if output_dir is None:
            output_dir = csv_path.parent
        else:
            output_dir = Path(output_dir)

        safe_outcome = re.sub(r'[^\w]', '_', outcome)
        json_path = output_dir / f'cv_result_{safe_outcome}.json'
        r_path = output_dir / f'cv_script_{safe_outcome}.R'

        # R 경로에서 백슬래시 처리 (Windows 호환)
        csv_str = str(csv_path).replace('\\', '/')
        json_str = str(json_path).replace('\\', '/')

        script = f"""\
# ============================================================
# Auto-generated by yod_diabetes_app CrossValidator
# Outcome: {outcome}
# Python Fine-Gray (IPCW 근사) vs R cmprsk::crr() 교차 검증
# ============================================================

if (!requireNamespace("cmprsk", quietly = TRUE)) {{
  stop(paste(
    "cmprsk 패키지가 설치되지 않았습니다.",
    "R 콘솔에서 다음을 실행하세요: install.packages('cmprsk')",
    sep = "\\n"
  ))
}}
if (!requireNamespace("jsonlite", quietly = TRUE)) {{
  stop("jsonlite 패키지가 필요합니다: install.packages('jsonlite')")
}}

library(cmprsk)
library(jsonlite)

# 데이터 로드
data <- read.csv("{csv_str}", stringsAsFactors = FALSE)
cat(sprintf("데이터 로드: %d 행\\n", nrow(data)))

# 필수 컬럼 확인
required_cols <- c("time", "event_type")
missing <- setdiff(required_cols, names(data))
if (length(missing) > 0) {{
  stop(paste("필수 컬럼 누락:", paste(missing, collapse = ", ")))
}}

# 공변량 컬럼 자동 감지 (time, event_type 제외)
covar_cols <- setdiff(names(data), c("time", "event_type"))
if (length(covar_cols) == 0) {{
  stop("공변량 컬럼이 없습니다.")
}}
cat(sprintf("공변량: %s\\n", paste(covar_cols, collapse = ", ")))

ftime   <- data$time
fstatus <- as.integer(data$event_type)
cov1    <- as.matrix(data[, covar_cols, drop = FALSE])

# crr() 실행 — failcode=1(관심사건), cencode=0(검열)
cat("cmprsk::crr() 실행 중...\\n")
fit <- tryCatch(
  crr(ftime, fstatus, cov1, failcode = 1, cencode = 0),
  error = function(e) stop(paste("crr() 실패:", conditionMessage(e)))
)

s <- summary(fit)

# 결과 추출
coef_mat   <- s$coef
conf_mat   <- s$conf.int   # [, "exp(coef)", "exp(-coef)", "2.5%", "97.5%"]

result_list <- vector("list", length(covar_cols))
for (i in seq_along(covar_cols)) {{
  result_list[[i]] <- list(
    covariate = covar_cols[i],
    coef      = as.numeric(coef_mat[i, "coef"]),
    se        = as.numeric(coef_mat[i, "se(coef)"]),
    hr        = as.numeric(conf_mat[i, "exp(coef)"]),
    ci_lower  = as.numeric(conf_mat[i, "2.5 %"]),
    ci_upper  = as.numeric(conf_mat[i, "97.5 %"]),
    p_value   = as.numeric(coef_mat[i, "p-value"]),
    n         = fit$n,
    n_event   = fit$n.event[1]
  )
}}

# JSON 저장
write(toJSON(result_list, pretty = TRUE, auto_unbox = TRUE), "{json_str}")
cat(sprintf("결과 저장: %s\\n", "{json_str}"))
cat("SUCCESS\\n")
"""

        r_path.write_text(script, encoding='utf-8')
        logger.info("R 스크립트 생성: %s", r_path)
        return r_path

    def run_r_script(
        self,
        r_script_path: Path,
        timeout: int = _DEFAULT_R_TIMEOUT,
    ) -> dict | None:
        """R 스크립트를 subprocess로 실행하고 결과 JSON을 파싱한다.

        Args:
            r_script_path: generate_r_script()가 반환한 .R 파일 경로
            timeout: subprocess 타임아웃 (초, 기본 300)

        Returns:
            {covariate: {hr, ci_lower, ci_upper, p_value, coef, se, n, n_event}}
            R 미설치 또는 실패 시 None
        """
        r_script_path = Path(r_script_path)

        # Rscript 설치 여부 확인
        rscript = shutil.which('Rscript')
        if rscript is None:
            logger.info(
                "Rscript를 찾을 수 없습니다. R 교차 검증을 건너뜁니다. "
                "수동 실행: Rscript --vanilla %s", r_script_path
            )
            return None

        logger.info("R 스크립트 실행: %s (timeout=%ds)", r_script_path, timeout)
        try:
            proc = subprocess.run(
                [rscript, '--vanilla', str(r_script_path)],
                capture_output=True,
                text=True,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired:
            logger.error(
                "R 스크립트 타임아웃 (%ds 초과). "
                "수동 실행: Rscript --vanilla %s",
                timeout, r_script_path
            )
            return None
        except OSError as e:
            logger.error("R 스크립트 실행 오류: %s", e)
            return None

        if proc.returncode != 0:
            stderr_preview = (proc.stderr or '')[:500]
            logger.error(
                "R 스크립트 실패 (returncode=%d):\n%s\n"
                "수동 실행: Rscript --vanilla %s",
                proc.returncode, stderr_preview, r_script_path
            )
            # cmprsk 미설치 안내
            if 'cmprsk' in stderr_preview or 'jsonlite' in stderr_preview:
                logger.error(
                    "R 패키지 미설치로 인한 실패. R 콘솔에서 실행하세요:\n"
                    "  install.packages(c('cmprsk', 'jsonlite'))"
                )
            return None

        # JSON 결과 파일 탐색 (스크립트와 같은 디렉토리)
        json_candidates = list(r_script_path.parent.glob('cv_result_*.json'))
        if not json_candidates:
            logger.error("R 실행 성공 but JSON 결과 파일 없음 (디렉토리: %s)", r_script_path.parent)
            return None

        # 스크립트명과 같은 stem 우선 선택
        target_stem = r_script_path.stem.replace('cv_script_', 'cv_result_')
        json_path = next(
            (p for p in json_candidates if p.stem == target_stem),
            json_candidates[0]
        )

        try:
            raw = json.loads(json_path.read_text(encoding='utf-8'))
        except (json.JSONDecodeError, OSError) as e:
            logger.error("R 결과 JSON 파싱 실패 (%s): %s", json_path, e)
            return None

        # list of {covariate, hr, ...} → dict keyed by covariate
        if isinstance(raw, list):
            parsed = {item['covariate']: item for item in raw if 'covariate' in item}
        elif isinstance(raw, dict):
            parsed = raw
        else:
            logger.error("R 결과 JSON 구조 예상 외: %s", type(raw))
            return None

        logger.info("R crr() 완료: %d개 공변량 결과 파싱", len(parsed))
        return parsed

    def compare_results(
        self,
        python_summary: pd.DataFrame | None,
        r_results: dict | None,
        tolerance_pct: float = 5.0,
    ) -> pd.DataFrame:
        """Python Fine-Gray 결과와 R crr() 결과를 비교한다.

        Args:
            python_summary: cph.summary (lifelines CoxPHFitter.summary DataFrame)
            r_results: run_r_script() 반환값
            tolerance_pct: HR 차이 허용 퍼센트 (기본 5%)

        Returns:
            비교 테이블 DataFrame. 컬럼:
              covariate, py_hr, py_ci_lower, py_ci_upper, py_p,
              r_hr, r_ci_lower, r_ci_upper, r_p,
              hr_diff_pct, concordant, note
        """
        rows = []

        # Python 결과 파싱
        py_data: dict[str, dict] = {}
        if python_summary is not None and not python_summary.empty:
            for cov in python_summary.index:
                try:
                    py_data[cov] = {
                        'hr':       float(python_summary.loc[cov, 'exp(coef)']),
                        'ci_lower': float(python_summary.loc[cov, 'exp(coef) lower 95%']),
                        'ci_upper': float(python_summary.loc[cov, 'exp(coef) upper 95%']),
                        'p':        float(python_summary.loc[cov, 'p']),
                    }
                except (KeyError, TypeError):
                    logger.debug("Python summary 파싱 실패 (공변량: %s)", cov)

        # 공변량 합집합
        all_covars = sorted(set(py_data.keys()) | set((r_results or {}).keys()))

        for cov in all_covars:
            py = py_data.get(cov, {})
            r = (r_results or {}).get(cov, {})

            py_hr = py.get('hr', np.nan)
            r_hr  = r.get('hr', np.nan)

            if not np.isnan(py_hr) and not np.isnan(r_hr) and r_hr != 0:
                hr_diff_pct = abs(py_hr - r_hr) / r_hr * 100
                concordant  = bool(hr_diff_pct <= tolerance_pct)
                note = '' if concordant else f'차이 {hr_diff_pct:.1f}% > 허용 {tolerance_pct}%'
            elif r_results is None:
                hr_diff_pct = np.nan
                concordant  = False
                note = 'R 결과 없음'
            else:
                hr_diff_pct = np.nan
                concordant  = False
                note = 'HR 계산 불가'

            rows.append({
                'covariate':   cov,
                'py_hr':       round(py_hr, 4) if not np.isnan(py_hr) else np.nan,
                'py_ci_lower': round(py.get('ci_lower', np.nan), 4),
                'py_ci_upper': round(py.get('ci_upper', np.nan), 4),
                'py_p':        round(py.get('p', np.nan), 6),
                'r_hr':        round(r_hr, 4) if not np.isnan(r_hr) else np.nan,
                'r_ci_lower':  round(r.get('ci_lower', np.nan), 4),
                'r_ci_upper':  round(r.get('ci_upper', np.nan), 4),
                'r_p':         round(r.get('p_value', np.nan), 6),
                'hr_diff_pct': round(hr_diff_pct, 2) if not np.isnan(hr_diff_pct) else np.nan,
                'concordant':  concordant,
                'note':        note,
            })

        return pd.DataFrame(rows)

    @staticmethod
    def validation_status(comparison_df: pd.DataFrame, r_available: bool) -> str:
        """비교 결과로부터 validation_status를 결정한다.

        Returns:
            'VALIDATED'          - 모든 공변량 HR 차이 허용 범위 이내
            'DISCREPANT'         - 1개 이상 공변량 HR 차이 허용 범위 초과
            'R_NOT_AVAILABLE'    - Rscript 미설치
            'NO_COMPARISON_DATA' - 비교 데이터 없음
        """
        if not r_available:
            return 'R_NOT_AVAILABLE'
        if comparison_df is None or comparison_df.empty:
            return 'NO_COMPARISON_DATA'
        if comparison_df['concordant'].all():
            return 'VALIDATED'
        return 'DISCREPANT'

    @staticmethod
    def cleanup_temp_files(paths: list[str | Path], ignore_errors: bool = True) -> None:
        """임시 CSV / R 스크립트 / JSON 파일을 삭제한다.

        Args:
            paths: 삭제할 파일 경로 목록
            ignore_errors: True이면 삭제 실패 시 경고 로깅 후 계속 (기본 True)
        """
        for p in paths:
            try:
                path = Path(p)
                if path.exists():
                    path.unlink()
                    logger.debug("임시 파일 삭제: %s", path)
            except OSError as e:
                if ignore_errors:
                    logger.warning("임시 파일 삭제 실패 (무시): %s — %s", p, e)
                else:
                    raise

    @staticmethod
    def cleanup_temp_dir(dir_path: str | Path, ignore_errors: bool = True) -> None:
        """임시 디렉토리 전체를 삭제한다."""
        try:
            shutil.rmtree(str(dir_path), ignore_errors=ignore_errors)
            logger.debug("임시 디렉토리 삭제: %s", dir_path)
        except OSError as e:
            logger.warning("임시 디렉토리 삭제 실패: %s — %s", dir_path, e)
